### ISSUE TITLE
Cannot read property 'formats' of undefined

### ISSUE THREAD

**Issue by Jtreix** [intljusticemission/react-big-calendar#1063]
#### Do you want to request a _feature_ or report a _bug_?
Bug.
#### What's the current behavior?

> TypeError: Cannot read property 'formats' of undefined
![image](https://user-images.githubusercontent.com/39380337/47488108-60ec1980-d84c-11e8-84bf-047c43efc30c.png)

When I delete the bigcalendar class, the problem is solved. lol.
![image](https://user-images.githubusercontent.com/39380337/47488141-6c3f4500-d84c-11e8-9073-bd61dff847b7.png)

#### What's the expected behavior?
All of copied from your examples. But doesnt works.

**Comment by Jtreix** [comment]
`My problems is solved, i set localizer props to moment.js.
`![image](https://user-images.githubusercontent.com/39380337/47494396-33a66800-d85a-11e8-82ca-0b8fe0bebd44.png)

**Comment by jquense** [comment]
I would declare your localizer up out of the render() method personally but if what you have works great 👍

**Comment by michaelwybraniec** [comment]
What if it does not resolve the issue?  

**const localizer = BigCalendar.momentLocalizer(moment);**

**Comment by afurman-ralabs** [comment]
The same issue occured:
TypeError: Cannot read property 'formats' of undefined
    "react-big-calendar": "^0.30.0",
took example from here:
https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js

**Comment by afurman-ralabs** [comment]
The case with separate localized didn't resolve the issue:
const localizer = BigCalendar.momentLocalizer(moment);

**Comment by yash-zorp** [comment]
`localizer={DragAndDropCalendar.momentLocalizer(moment)}`
TypeError: DragAndDropCalendar.momentLocalizer is not a function. What to do now?
